name = "CDAWeb"
uuid = "950ff2a9-823f-469c-91a7-754a5d85edca"
version = "0.1.3"
authors = ["Beforerr <zzj956959688@gmail.com> and contributors"]

[deps]
CDFDatasets = "075ae62b-f872-4368-b383-31e3aa6c3154"
DBInterface = "a10d1c49-ce27-4219-8d33-6db1a4562965"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
ResumableFunctions = "c5292f4c-5179-55e1-98c5-05642aab7184"
SQLite = "0aa819cd-b072-5ff4-a722-6bc24af294d9"
Tar = "a4e569a6-e804-4fa4-b0f3-eef7a1d5b13e"
TypedTables = "9d95f2ec-7b3d-5a63-8d20-e2491e220bb9"

[compat]
CDFDatasets = "0.1.3"
DBInterface = "2"
Dates = "1"
Downloads = "1"
HTTP = "1"
JSON3 = "1"
ResumableFunctions = "1"
SQLite = "1"
Tar = "1"
TypedTables = "1.4"
julia = "1.10"
